quarkus:
  http:
    port: 8008
  datasource:
    db-kind: postgresql
    username: sam
    password: password
    jdbc:
      url: jdbc:postgresql://localhost:5432/quarkus
      max-size: 16
  hibernate-orm:
    database:
      generation: update
    unsupported-properties:
      "hibernate.physical_naming_strategy": org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


  oidc:
    auth-server-url: http://localhost:8080/realms/QUARKUS

#  smallrye-openapi:
#    path: /swagger


  live-reload:
    instrumentation: true
